
project_id = "dnhdqhvvsefxzcejlkrq"

[functions.get-guest-photos]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-subscription-session]
verify_jwt = false

[functions.check-subscription-status]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = false

[functions.get-dashboard-stats]
verify_jwt = false

[functions.get-sales-trends]
verify_jwt = false
