// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dnhdqhvvsefxzcejlkrq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRuaGRxaHZ2c2VmeHpjZWpsa3JxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMTI0NDcsImV4cCI6MjA2MDY4ODQ0N30.kHwbWdzsOE04inlp0bjFmCFCDlIEHhFO2_JRMZn3oy4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);